//
//  MainInteractor.swift
//  ShareToIG
//
//  Created by 바보세림이 on 2020/09/06.
//  Copyright (c) 2020 serim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func shareToInstaStories(imageForShare: UIImage)
    func doSomething(request: Main.Share.Request)
}

protocol MainDataStore {
    // var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    // var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Main.Share.Request) {
        worker = MainWorker()
        worker?.doSomeWork()
        
        let response = Main.Share.Response()
        presenter?.presentSomething(response: response)
    }
    
    func shareToInstaStories(imageForShare: UIImage) {
        if let storiesUrl = URL(string: "instagram-stories://share") {
            if UIApplication.shared.canOpenURL(storiesUrl) {
                let image = imageForShare
                guard let imageData = image.pngData() else { return  }
                let pasteboardItems: [String:Any] = [
                    "com.instagram.sharedSticker.stickerImage":imageData,
                    "com.instagram.sharedSticker.backgroundTopColor":"#A9E2F3",
                    "com.instagram.sharedSticker.backgroundBottomColo":"#2ECCFA"
                ]
                let pasteboardOptions = [
                    UIPasteboard.OptionsKey.expirationDate: Date().addingTimeInterval(500)
                ]
                UIPasteboard.general.setItems([pasteboardItems], options: pasteboardOptions)
                UIApplication.shared.open(storiesUrl, options: [:], completionHandler: nil)
            } else {
                print("User doesn't have insta app.")
            }
        }
    }
}
