//
//  MainModels.swift
//  ShareToIG
//
//  Created by 바보세림이 on 2020/09/06.
//  Copyright (c) 2020 serim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
    
    // MARK: Use cases
    
    enum Something {
        struct Request { }
        struct Response { }
        struct ViewModel { }
    }
}

